development:
  bitcoin:
    storage_key: "btc_usd"
    request_url: "https://bitbay.net/API/Public/BTCUSD/ticker.json"
  ethereum:
    storage_key: "eth_usd"
    request_url: "https://bitbay.net/API/Public/ETHUSD/ticker.json"  
  nasdaq:
    response_processor: "NasdaqResponseProcessor"
    request_url: "https://www.quandl.com/api/v3/datasets/NASDAQOMX/COMP.json?api_key=2GP6dWmCuicpm3d5sTiX"  
test:
  bitcoin:
    storage_key: "btc_usd"
    request_url: "https://bitbay.net/API/Public/BTCUSD/ticker.json"
  ethereum:
    storage_key: "eth_usd"
    request_url: "https://bitbay.net/API/Public/ETHUSD/ticker.json" 
  nasdaq:
    response_processor: "NasdaqResponseProcessor"
    request_url: "https://www.quandl.com/api/v3/datasets/NASDAQOMX/COMP.json?api_key=2GP6dWmCuicpm3d5sTiX"       
production:     
  bitcoin:
    storage_key: "btc_usd"
    request_url: "https://bitbay.net/API/Public/BTCUSD/ticker.json"
  ethereum:
    storage_key: "eth_usd"
    request_url: "https://bitbay.net/API/Public/ETHUSD/ticker.json"
  nasdaq:
    response_processor: "NasdaqResponseProcessor"
    request_url: "https://www.quandl.com/api/v3/datasets/NASDAQOMX/COMP.json?api_key=2GP6dWmCuicpm3d5sTiX"  