development:
  bitcoin:
    storage_key: "btc_usd"
    request_url: "https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=USD"
  ethereum:
    storage_key: "eth_usd"
    request_url: "https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=USD"  
  nasdaq:
    response_processor: "NasdaqResponseProcessor"
    request_url: "https://www.quandl.com/api/v3/datasets/NASDAQOMX/COMP.json?api_key=2GP6dWmCuicpm3d5sTiX&rows=100"  
test:
  bitcoin:
    storage_key: "btc_usd"
    request_url: "https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=USD"
  ethereum:
    storage_key: "eth_usd"
    request_url: "https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=USD" 
  nasdaq:
    response_processor: "NasdaqResponseProcessor"
    request_url: "https://www.quandl.com/api/v3/datasets/NASDAQOMX/COMP.json?api_key=2GP6dWmCuicpm3d5sTiX&rows=100"       
production:     
  bitcoin:
    storage_key: "btc_usd"
    request_url: "https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=USD"
  ethereum:
    storage_key: "eth_usd"
    request_url: "https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=USD"
  nasdaq:
    response_processor: "NasdaqResponseProcessor"
    request_url: "https://www.quandl.com/api/v3/datasets/NASDAQOMX/COMP.json?api_key=2GP6dWmCuicpm3d5sTiX&rows=100"  