default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: charts_development
  pool: 10
test:
  <<: *default
  database: charts_test
production:
  <<: *default
  database: charts_production
  username: charts
  password: <%= ENV.fetch("PROD_DB_PASSWORD") %>
staging:
  <<: *default
  database: charts_staging
  username: charts
  password: charts
  pool: 10
  